#
# lkn: an actor-based multiplayer game engine
# Copyright (C) 2017 Thomas “Letan <contact@thomasletan.fr>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
---
- hosts: lethio
  remote_user: root
  tasks:
    - name: create root directory if necessary
      become: yes
      become_user: www-data
      file:
        path: /srv/lkn/lkn
        state: directory
    - name: create docs directory if necessary
      become: yes
      become_user: www-data
      file:
        path: /srv/lkn/lkn/docs
        state: directory
    - name: create cover directory if necessary
      become: yes
      become_user: www-data
      file:
        path: /srv/lkn/lkn/cover
        state: directory
    - name: copy docs
      synchronize:
        owner: no
        group: no
        src: ../doc/
        dest: /srv/lkn/lkn/docs
    - name: doc ownership
      file:
        path: /srv/lkn/lkn/docs
        recurse: yes
        owner: www-data
        group: www-data
    - name: copy cover
      synchronize:
        owner: no
        group: no
        src: ../cover/
        dest: /srv/lkn/lkn/cover
    - name: cover ownership
      file:
        path: /srv/lkn/lkn/cover
        recurse: yes
        owner: www-data
        group: www-data
